{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedStrings #-}

module Lamdera.PackageReplacementsTH (loadReplacements, loadVersions) where

import Control.Exception (throwIO)
import Control.Monad (forM)
import qualified Data.ByteString as B
import qualified Data.List as List
import qualified Data.Map as Map
import qualified Data.Maybe as Maybe
import qualified Data.Name as Name
import qualified Data.Utf8 as Utf8
import qualified Elm.ModuleName as ModuleName
import qualified Elm.Package as Pkg
import qualified Elm.Version as V
import qualified Json.Decode as D
import qualified Language.Haskell.TH as TH
import qualified Language.Haskell.TH.Syntax
import qualified System.Directory as Dir
import qualified System.FilePath as FP
import System.FilePath ((</>))
import qualified System.Process


root :: FilePath
root = "extra" </> "package-replacements"


-- This file is generated by extra/package-replacements/lock.sh.
-- It is used to make sure that the Template Haskell in this file
-- is re-run as the package replacements change.
lock :: FilePath
lock = root </> "lock.txt"


loadReplacements :: TH.Q TH.Exp
loadReplacements = do
  Language.Haskell.TH.Syntax.addDependentFile lock
  submodules <- TH.runIO findSubmodules
  listItems <- submodulesToReplacementsListItems submodules
  [| Map.fromList $(pure (TH.ListE listItems)) |]


loadVersions :: TH.Q TH.Exp
loadVersions = do
  Language.Haskell.TH.Syntax.addDependentFile lock
  submodules <- TH.runIO findSubmodules
  listItems <- submodulesToVersionsListItems submodules
  [| $(pure (TH.ListE listItems)) |]


submodulesToReplacementsListItems :: [Submodule] -> TH.Q [TH.Exp]
submodulesToReplacementsListItems submodules =
  fmap List.concat $
    forM submodules $ \(author, project, dir) -> do
      changedFiles <- TH.runIO (gitChangedFilesIn dir)
      let modules = Maybe.mapMaybe (\filePath -> fmap (filePath,) (parseModuleName filePath)) changedFiles
      forM modules $ \(filePath, moduleName) -> do
        bytes <- TH.runIO (B.readFile (dir </> filePath))

        [|
          ( ( Pkg.toName (Utf8.fromChars author) project
            , Name.fromChars moduleName
            )
          , $(Language.Haskell.TH.Syntax.lift bytes)
          )
         |]


submodulesToVersionsListItems :: [Submodule] -> TH.Q [TH.Exp]
submodulesToVersionsListItems submodules =
  forM submodules $ \(author, project, dir) -> do
    V.Version major minor patch <- TH.runIO (readVersion dir)
    commit <- TH.runIO (gitCommitHashIn dir)
    [|
      ( Pkg.toName (Utf8.fromChars author) project
      , V.Version major minor patch
      , commit
      )
     |]


type Submodule =
  ( String -- author
  , String -- project
  , FilePath -- directory
  )


findSubmodules :: IO [Submodule]
findSubmodules = do
  authors <- listDirectory root
  fmap (List.sort . List.concat) $
    forM authors $ \author -> do
      let dir = root </> author
      projects <- listDirectory dir
      pure (fmap (\project -> (author, project, dir </> project)) projects)


listDirectory :: FilePath -> IO [FilePath]
listDirectory dir = do
  items <- Dir.listDirectory dir
  pure (List.filter (notElem '.') items) -- Skip items with a period – which likely are files.


gitChangedFilesIn :: FilePath -> IO [FilePath]
gitChangedFilesIn dir = do
  stdout <- System.Process.readProcess "git" ["-C", dir, "diff", "origin/master...", "--name-only"] ""
  pure (lines stdout)


gitCommitHashIn :: FilePath -> IO String
gitCommitHashIn dir = do
  stdout <- System.Process.readProcess "git" ["-C", dir, "rev-parse", "HEAD"] ""
  pure (init stdout) -- Drop trailing newline.


parseModuleName :: FilePath -> Maybe String
parseModuleName filePath =
  let
    ext =
      FP.takeExtension filePath
  in
  if ext == ".js" || ext == ".elm" then
    case FP.splitDirectories (FP.dropExtension filePath) of
      "src" : rest ->
        Just (List.intercalate "." rest)

      _ ->
        Nothing

  else
    Nothing


readVersion :: FilePath -> IO V.Version
readVersion dir = do
  let elmJsonPath = dir </> "elm.json"
  bytes <- B.readFile elmJsonPath
  case D.fromByteString (D.field "version" V.decoder) bytes of
    Left _ ->
      throwIO (userError ("Failed to decode version from: " <> elmJsonPath))

    Right version ->
      return version
