library:
  source-dirs:
  - src
  exposed-modules: []
ghc-options: -Wall -Werror
dependencies:
- lamdera-haskelm
- elm-delim-browser
- elm-delim-core
- elm-delim-html
- elm-delim-json
- elm-delim-random
- elm-delim-time
- elm-delim-url
- elm-delim-virtual-dom
- mgold-delim-elm-nonempty-list
- zwilias-delim-json-decode-exploration
default-extensions:
- ConstraintKinds
- TypeFamilies
- TypeOperators
- OverloadedStrings
- OverloadedLabels
- DataKinds
- NoImplicitPrelude
- DeriveAnyClass
- NoMonomorphismRestriction
- GADTs
- StandaloneDeriving
- FlexibleContexts
name: lamdera-elm-main
version: 0.0.1
synopsis: lamdera elm main entrypoint
license: notApplicable
