packages:
- .
extra-deps:
- elm-home/0.19.0/lamdera/haskelm
- elm-home/0.19.0/package/zwilias/json-decode-exploration/5.0.1/haskelm
- elm-home/0.19.0/package/elm/core/1.0.0/haskelm
- elm-home/0.19.0/package/elm/html/1.0.0/haskelm
- elm-home/0.19.0/package/elm/url/1.0.0/haskelm
- elm-home/0.19.0/package/elm/time/1.0.0/haskelm
- elm-home/0.19.0/package/elm/browser/1.0.0/haskelm
- elm-home/0.19.0/package/elm/json/1.0.0/haskelm
- elm-home/0.19.0/package/elm/virtual-dom/1.0.0/haskelm
- elm-home/0.19.0/package/elm/random/1.0.0/haskelm
- elm-home/0.19.0/package/mgold/elm-nonempty-list/4.0.0/haskelm
- acid-state-0.14.3
- regexpr-0.5.4
- superrecord-0.5.0.1
- unagi-chan-0.4.1.0
- mtlparse-0.1.4.0
resolver: lts-11.9
require-stack-version: ! '>= 1.4.0'
