module Migrate_Nested_Dict.Expected exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Lamdera.Migrations exposing (..)
import Migrate_Nested_Dict.New
import Migrate_Nested_Dict.Old


target =
    migrate_Migrate_Nested_Dict_New_Target


migrate_Migrate_Nested_Dict_New_Target : Migrate_Nested_Dict.Old.Target -> Migrate_Nested_Dict.New.Target
migrate_Migrate_Nested_Dict_New_Target old =
    case old of
        Migrate_Nested_Dict.Old.Wrapper p0 ->
            Migrate_Nested_Dict.New.Wrapper (p0 |> Dict.toList |> List.map (Tuple.mapBoth (Unimplemented {- Type changed from `Int` to `String`. I need you to write this migration. -}) (\v__ -> v__ |> Dict.toList |> List.map (Tuple.mapFirst (Unimplemented {- Type changed from `Int` to `String`. I need you to write this migration. -})) |> Dict.fromList)) |> Dict.fromList)
