# Updates cabal freeze to latest then replaces dependencies pinning with stack's calculations

cd ..

cabal freeze

awk '
  BEGIN {
    print "--- generated by distribution/sync-cabal-freeze.sh"
    skip = 0
  }
  # When we hit the top-level "constraints:" key, print fresh output and start skipping the old block
  /^constraints:/ {
    cmd = "stack ls dependencies cabal"
    while ((cmd | getline line) > 0) print line
    close(cmd)
    skip = 1
    next
  }
  # End of the block = next top-level key (non-indented)
  skip && /^[^[:space:]]/ { skip = 0 }
  # While skipping, drop lines
  skip { next }
  # Otherwise, pass-through
  { print }
' cabal.project.freeze > cabal.project.freeze.new && mv cabal.project.freeze.new cabal.project.freeze
