module Migrate_Union_Renamed.Expected exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Lamdera.Migrations exposing (..)
import Migrate_Union_Renamed.New
import Migrate_Union_Renamed.Old


target =
    migrate_Migrate_Union_Renamed_New_Target


migrate_Migrate_Union_Renamed_New_CompanyType : Migrate_Union_Renamed.Old.MoralType -> Migrate_Union_Renamed.New.CompanyType
migrate_Migrate_Union_Renamed_New_CompanyType old =
    case old of
        Migrate_Union_Renamed.Old.Individual ->
            Migrate_Union_Renamed.New.Individual

        Migrate_Union_Renamed.Old.Corporation ->
            Migrate_Union_Renamed.New.Corporation


migrate_Migrate_Union_Renamed_New_Target : Migrate_Union_Renamed.Old.Target -> Migrate_Union_Renamed.New.Target
migrate_Migrate_Union_Renamed_New_Target old =
    case old of
        Migrate_Union_Renamed.Old.Wrapper p0 ->
            Migrate_Union_Renamed.New.Wrapper (p0 |> migrate_Migrate_Union_Renamed_New_CompanyType)
