#!/usr/bin/env bash
set -e

file="${BASH_SOURCE[0]:-$0}"
dir="$(dirname "$file")"

# If you have changed files in the git submodules in extra/package-replacements/
# you need to run this script to make sure that PackageReplacements.hs
# is recompiled (via Template Haskell in PackageReplacementsTH.hs).
# During development, run lock.sh without any arguments after each change
# to force recompilation.
# When ready to commit submodule changes, run `lock.sh commit` to write
# the hash of each submodule to the lock.txt file, so that other contributors
# automatically get one single recompilation as needed.
if test "$1" = commit; then
    echo "Generated by $file"
    # A leading plus sign means that the submodule is on a different commit than recorded.
    # Usually, we want to commit changes to submodules and the lock file at the same time,
    # so turn the plus into a space (just like it will be after committing the submodules).
    git submodule status "$dir" | sed 's/^+/ /'
else
    echo "DO NOT MERGE LIKE THIS - see $file"
    date
fi >"$dir/lock.txt"
