on:
  push:
    branches:
      - lamdera-next
  pull_request:

name: Test
jobs:
  test:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: freckle/stack-cache-action@v2

      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install ghcup & stack
        run: |
          mkdir -p ~/.local/bin
          curl https://downloads.haskell.org/~ghcup/aarch64-apple-darwin-ghcup -o ~/.local/bin/ghcup && chmod a+x ~/.local/bin/ghcup
          ghcup install stack recommended
          ghcup set stack recommended

      - name: Set up test environment
        env:
          SSH_KEY: ${{ secrets.GH_USER_SCP_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone --depth 1 git@github.com:lamdera/runtime.git _runtime
          mkdir -p ~/lamdera
          ln -s $GITHUB_WORKSPACE/_runtime/overrides ~/lamdera/overrides
          mkdir -p ~/elm-home-elmx-test

      - name: Build & run tests
        run: stack test
